Algoritmo "Algoritmo de soma utilizando procedimento"

Var

   A, B: Inteiro
   
Procedimento Soma(X, Y: Inteiro)

Inicio

   EscrevaL("------------------")
   EscrevaL("Recebi o valor:", X)
   EscrevaL("Recebi o valor:", Y)
   EscrevaL("A soma vale", X + Y)
   EscrevaL("------------------")

FimProcedimento

Inicio

   Escreva("Digite o primeiro valor: ")
   Leia(A)
   Escreva("Digite o segundo valor: ")
   Leia(B)
   
   Soma(A, B)

Fimalgoritmo