Algoritmo "Contar até 10 usando a estrutura para"

Var

   c: inteiro

Inicio

      Escreval("-----------------------------")
      Para c <- 1 ate 10 faca
        Escreval(c)
      FimPara

      Escreval("-----------------------------")
      Para c <- 5 ate 10 passo 1 faca
        Escreval(c)
      FimPara
      
      Escreval("-----------------------------")
      Para c <- 10 ate 1 passo -1 faca
        Escreval(c)
      FimPara

Fimalgoritmo